In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv(r'C:\Users\ganes\Desktop\dsbda practicals\parnavv\Iris.csv')

x = df.iloc[:, :4].values
y = df['Species'].values

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
print(x)
print(y)

[[  1.    5.1   3.5   1.4]
 [  2.    4.9   3.    1.4]
 [  3.    4.7   3.2   1.3]
 [  4.    4.6   3.1   1.5]
 [  5.    5.    3.6   1.4]
 [  6.    5.4   3.9   1.7]
 [  7.    4.6   3.4   1.4]
 [  8.    5.    3.4   1.5]
 [  9.    4.4   2.9   1.4]
 [ 10.    4.9   3.1   1.5]
 [ 11.    5.4   3.7   1.5]
 [ 12.    4.8   3.4   1.6]
 [ 13.    4.8   3.    1.4]
 [ 14.    4.3   3.    1.1]
 [ 15.    5.8   4.    1.2]
 [ 16.    5.7   4.4   1.5]
 [ 17.    5.4   3.9   1.3]
 [ 18.    5.1   3.5   1.4]
 [ 19.    5.7   3.8   1.7]
 [ 20.    5.1   3.8   1.5]
 [ 21.    5.4   3.4   1.7]
 [ 22.    5.1   3.7   1.5]
 [ 23.    4.6   3.6   1. ]
 [ 24.    5.1   3.3   1.7]
 [ 25.    4.8   3.4   1.9]
 [ 26.    5.    3.    1.6]
 [ 27.    5.    3.4   1.6]
 [ 28.    5.2   3.5   1.5]
 [ 29.    5.2   3.4   1.4]
 [ 30.    4.7   3.2   1.6]
 [ 31.    4.8   3.1   1.6]
 [ 32.    5.4   3.4   1.5]
 [ 33.    5.2   4.1   1.5]
 [ 34.    5.5   4.2   1.4]
 [ 35.    4.9   3.1   1.5]
 [ 36.    5.    3.2   1.2]
 [ 37.    5.5   3.5   1.3]
 

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train)
print(x_test)

[[-8.73239502e-01 -3.97218376e-01  1.06776981e+00 -1.40687635e+00]
 [-9.47549392e-02 -2.70782818e-01 -1.21622979e+00  1.07773136e-01]
 [-4.01430676e-01  6.14266082e-01  6.10969893e-01  5.73819132e-01]
 [ 1.27349066e+00  3.61394968e-01 -7.42299870e-02  6.90330631e-01]
 [-1.25068656e+00 -5.23653933e-01  8.39369853e-01 -1.17385335e+00]
 [ 2.59101680e-01 -5.23653933e-01 -7.42299870e-02  4.57307633e-01]
 [ 6.60139182e-01 -1.79117039e-02 -7.59429867e-01  8.06842130e-01]
 [ 9.66814919e-01 -1.79117039e-02 -5.31029907e-01  8.06842130e-01]
 [-3.54249793e-01  9.93572754e-01 -3.02629947e-01  5.15563382e-01]
 [ 4.71415652e-01 -1.02939616e+00 -1.67302971e+00 -2.41761360e-01]
 [-5.19382883e-01  7.40701639e-01  3.82569933e-01  4.57307633e-01]
 [ 1.62734728e+00 -1.79117039e-02 -7.59429867e-01  8.06842130e-01]
 [ 1.32067154e+00  1.75218610e+00 -7.42299870e-02  1.21463238e+00]
 [-7.78877737e-01 -1.02939616e+00  1.06776981e+00 -1.40687635e+00]
 [-4.95792441e-01  1.37287943e+00  1.54169973e-01  6.90330631e

In [8]:
from sklearn.naive_bayes import GaussianNB

In [9]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)
print(classifier)

GaussianNB()


In [10]:
y_pred = classifier.predict(x_test)
print(y_pred)

['Iris-virginica' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica']


In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

cm

array([[10,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 12]], dtype=int64)

In [12]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

1.0
